import type { Metadata } from 'next'
import './globals.css'
import MainLayout from '../../context/MainLayout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='max-w-[1200px] mx-auto bg-gray-50 dark:bg-gray-900 text-gray-800 dark:text-gray-200 font-sans'>
        <MainLayout> {children}</MainLayout>
      </body>
    </html>
  )
}
